server:
  port: 11001

spring:
  application:
    name: provider-server
name: provider-server11000

#eureka配置
eureka:
  client:
    service-url:
      #需要注册给Eureka Server的地址，也就是将自己注册给哪一个Eureka Server
      defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka
  instance:
    #使用ip地址向Eureka注册
    prefer-ip-address: true
    #上面的配置已经可以使用ip注册了，但显示的还是主机名，所以这里设置显示的注册名
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
